[package]
name = "sync"
version = "0.1.0"
authors = ["Hanh <hanh425@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "scan_all"
harness = false

[[bin]]
name = "warp-cli"
path = "src/main/warp_cli.rs"

[[bin]]
name = "cli"
path = "src/main/cli.rs"

[[bin]]
name = "sign"
path = "src/main/sign.rs"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.8.4"
anyhow = "1.0.40"
thiserror = "1.0.25"
log = "0.4.14"
flexi_logger = {version="0.17.1", features = ["compress"]}
serde = {version = "1.0.126", features = ["derive"]}
serde_json = "1.0.64"
tokio = { version = "^1.6", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.7"
protobuf = "2.23.0"
hex = "0.4.3"
futures = "0.3.15"
tonic = {version = "0.4.3", features = ["tls", "tls-roots"]}
prost = "0.7"
rayon = "1.5.1"
tiny-bip39 = "0.8"
rand = "0.8.4"
rusqlite = { version = "^0.24", features = ["bundled"] }
jubjub = "^0.6"
bls12_381 = "^0.4.0"
ff = "^0.9"
group = "0.9.0"
byteorder = "^1.4"
secp256k1 = "0.20.2"
tiny-hderive = "0.3.0"
ripemd160 = "0.9.1"
sha2 = "0.9.5"
lazy_static = "1.4.0"
rustyline = "8.2.0"
clap = "3.0.0-beta.2"
chrono = "0.4.19"
reqwest = { version = "0.11.4", features = ["json", "rustls-tls"], default-features = false }

# librustzcash synced to 35023ed8ca2fb1061e78fd740b640d4eefcc5edd

[dependencies.zcash_client_backend]
git = "https://github.com/hhanh00/librustzcash.git"
branch = "warp-sync"

[dependencies.zcash_primitives]
git = "https://github.com/hhanh00/librustzcash.git"
branch = "warp-sync"
features = [ "transparent-inputs" ]

[dependencies.zcash_proofs]
git = "https://github.com/hhanh00/librustzcash.git"
branch = "warp-sync"

[dependencies.zcash_params]
git = "https://github.com/hhanh00/zcash-params.git"
branch = "main"

[build-dependencies]
tonic-build = "0.4.2"

[dev-dependencies]
criterion = "0.3.4"

[features]
ycash = []
