[package]
name = "sync"
version = "0.1.0"
authors = ["Hanh <hanh425@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
anyhow = "1.0.40"
log = "0.4.14"
flexi_logger = {version="0.17.1", features = ["compress"]}
serde = {version = "1.0.126", features = ["derive"]}
serde_json = "1.0.64"
tokio = { version = "^1.6", features = ["macros", "rt-multi-thread"] }
protobuf = "2.23.0"
jubjub = "0.6"
bls12_381 = "0.4.0"
ff = "0.9"
group = "0.9"
hex = "0.4.3"
bytes = "1.0.1"
futures = "0.3.15"
tonic = {version = "0.4.3", features = ["tls", "tls-roots"]}
prost = "0.7"
rayon = "1.5.1"

[dependencies.zcash_client_backend]
git = "https://github.com/zcash/librustzcash.git"
rev = "d50bb12a97da768dc8f3ee39b81f84262103e6eb"

[dependencies.zcash_primitives]
git = "https://github.com/zcash/librustzcash.git"
features = [ "transparent-inputs" ]
rev = "d50bb12a97da768dc8f3ee39b81f84262103e6eb"

[dependencies.zcash_proofs]
git = "https://github.com/zcash/librustzcash.git"
rev = "d50bb12a97da768dc8f3ee39b81f84262103e6eb"

[build-dependencies]
tonic-build = "0.4.2"
