[package]
name = "sync"
version = "0.1.0"
authors = ["Hanh <hanh425@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "scan_all"
harness = false

[dependencies]
dotenv = "0.15.0"
env_logger = "0.8.4"
anyhow = "1.0.40"
log = "0.4.14"
flexi_logger = {version="0.17.1", features = ["compress"]}
serde = {version = "1.0.126", features = ["derive"]}
serde_json = "1.0.64"
tokio = { version = "^1.6", features = ["macros", "rt-multi-thread"] }
protobuf = "2.23.0"
jubjub = "0.6"
bls12_381 = "0.4.0"
ff = "0.9"
group = "0.9"
hex = "0.4.3"
bytes = "1.0.1"
futures = "0.3.15"
tonic = {version = "0.4.3", features = ["tls", "tls-roots"]}
prost = "0.7"
rayon = "1.5.1"
byteorder = "1.4.3"

[dependencies.zcash_client_backend]
path = "../librustzcash/zcash_client_backend"

[dependencies.zcash_primitives]
path = "../librustzcash/zcash_primitives"

[dependencies.zcash_proofs]
path = "../librustzcash/zcash_proofs"

[build-dependencies]
tonic-build = "0.4.2"

[dev-dependencies]
criterion = "0.3.4"
